model = "dino"
embedding_dim = 1000
pipeline = 0
train = false
batch_size = 128

data_path="data/fiocruz/raw"
val_data_path="data/fiocruz/test_raw"
save_embedding_path="./embeddings/"
checkpoint_dir = "./checkpoints/embedding_models"
model_name = "imagenet"
mode="train"
prefix="fiocruz_dino"
load_checkpoint=false