model = "efficientnetb0"
embedding_dim = 1280
pipeline = 0
train = false
batch_size = 128

data_path="C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/embedding-retrieval/data/bracs-resized/train"
val_data_path="C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/embedding-retrieval/data/bracs-resized/test"
save_embedding_path="./embeddings/triplet"
checkpoint_dir = "./checkpoints/embedding_models"
model_name = "triplet"
mode="test"
prefix="bracs_effic"