model = "efficientnetb0_encoder"
embedding_dim = 12544
pipeline = "autoencoder"
batch_size = 32
inf_batch_size = 128
lr = 0.001
epochs = 100
data_path="data/fiocruz/raw"
val_data_path="data/fiocruz/test_raw"
save_embedding_path="./embeddings/"
prefix="fiocruz_efficient_finetune"
model_name = "autoencoder"