model="efficientnetb0"
embedding_dim=1280
pipeline="triplet"
batch_size =20
inf_batch_size=128
lr=0.001
epochs=100
data_path="data/fiocruz/raw"
val_data_path="data/fiocruz/test_raw"
save_embedding_path="./embeddings/"
triplet_dataset_classes=['Hypercellularity', 'Normal', 'Membranous', 'Sclerosis', 'Crescent', 'Podocytopathy']
triplet_categories_num = 6
prefix="fiocruz_efficient_finetune"
model_name = "triplet"

[model]
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]
img_size = [224, 224]