model = "swav"
embedding_dim = 1280
pipeline = "swav"
batch_size = 20
inf_batch_size = 128
lr = 0.001
epochs = 100
data_path="data/fiocruz/raw"
val_data_path="data/fiocruz/test_raw"
save_embedding_path="./embeddings/"
prefix="fiocruz_efficient_finetune"
model_name = "swav"