save_embedding_path = "./embeddings/final"

sem_basepath = "./embeddings/semantic_efficient_bracs/"
emb_basepath = "./embeddings/bracs_efficient_finetune/"

embeddings_train= [ "autoencoder_train.pickle", "swav_train.pickle", "triplet_train.pickle"]
embeddings_test= [ "autoencoder_test.pickle", "swav_test.pickle", "triplet_test.pickle"]

semantic_train = "efficientnet_train.pickle"
semantic_test = "efficientnet_test.pickle"

prefix="bracs_efficient_finetune"