model="efficientnetb0"
embedding_dim=1280
pipeline="triplet"
batch_size =20
inf_batch_size=128
lr=0.001
epochs=100
data_path="data/bracs/raw"
val_data_path="data/bracs/test"
save_embedding_path="./embeddings/"
triplet_dataset_classes=["0_N","1_PB","2_UDH","3_FEA","4_ADH","5_DCIS","6_IC"]
triplet_categories_num = 7
prefix="bracs_efficient_finetune"
model_name = "triplet"