wandb_project: 'debugging'
wandb_team: 'terumo-binary'
n_folds: 5
seed: 42
num_workers: 0
batch_size: 64
pin_memory: True
load_model: False
checkpoint_to_be_loaded: './artifacts/model/my_checkpoint.pth.tar'
learning_rate: 0.0001
num_epochs: 1
freeze: False
wandb_on: True
wandb_key: '273b6e50d83b95fd3a12d6544e5d48bf5afa49e2'
wandb_save_checkpoint: True
patience: 0
model_name: 'Debugging'
data_dir: './data/binary/binary_Hypercellularity'
classes: ['_others', 'Hypercellularity']
