model = "efficientnetb0"
embedding_dim = 1280
pipeline = 0
train = false
batch_size = 128

data_path="data/fiocruz/raw"
val_data_path="data/fiocruz/test_raw"
save_embedding_path="./embeddings/"
checkpoint_dir = "./checkpoints/embedding_models"
model_name = "imagenet"
mode="train"
prefix="fiocruz_efficient"
load_checkpoint=false

[model]
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]
img_size = [224, 224]